feat: hide password #181
E-cell-NITS/e-cell-website-22 pull request #189
Opened 2023-09-15 16:55 UTC by FabioSM46

Add checkbox to hide-show password in login sign up page

2023-09-15 17:56 UTC, hereisadi requested changes

2023-09-15 17:56 UTC, hereisadi commented on package-lock.json
pnpm-lock.yaml file is already created, so need to create another package-lock.json. Most probably, you used `npm i` to install the node_modules; rather use `pnpm i` to install the dependencies and delete the package-lock.json

2023-09-15 18:14 UTC, hereisadi commented
#181

2023-09-16 07:48 UTC, hereisadi commented
Thanks for the follow-up. There are some conflicts involved. Can you please, take a pull from `vite_newdev` branch?

2023-09-18 16:26 UTC, FabioSM46 commented
@hereisadi conflicts are solved.

2023-09-18 18:18 UTC, hereisadi approved these changes

2023-09-18 18:19 UTC, merged

2023-09-18 18:19 UTC, hereisadi commented
Thanks, merging!